//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appsuggest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class appsuggestEntities1 : DbContext
    {
        public appsuggestEntities1()
            : base("name=appsuggestEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppPlatform> AppPlatforms { get; set; }
        public virtual DbSet<App> Apps { get; set; }
        public virtual DbSet<AppType> AppTypes { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<State> States { get; set; }
    }
}
