//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appsuggest.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class Review
    {
        public int UserId { get; set; }
        public int AppId { get; set; }
        public int Rate { get; set; }
        public string ReviewText { get; set; }
        public string AppVersion { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
    
        public virtual App App { get; set; }
        public virtual User User { get; set; }
    }
}
